---

- name: Get current version
  shell: |
    set -o pipefail
    VBoxManage --version | grep "[0-9\.]r[0-9\.]" | sed "s/r.*//"
  args:
    executable: /bin/bash
  register: vbox_version
  changed_when: no
  check_mode: no

- name: Redefine minor version
  set_fact:
    virtbox_version_minor: "{{ vbox_version.stdout }}"

- name: Get Virtualbox extension packs installed
  shell: |
    set -o pipefail
    VBoxManage list extpacks | awk '/Version:/ {print $2}'
  args:
    executable: /bin/bash
  register: extpack_version
  check_mode: no
  changed_when: False

- name: Install extension pack
  block:

    - name: Download VirtualBox extension pack
      get_url:
        url: "{{ virtbox_extpack }}"
        dest: /tmp/{{ virtbox_extpack | basename }}
        #validate_certs: False

    - name: Install VirtualBox extension pack  # noqa no-changed-when
      shell: |
        echo 'y' | VBoxManage extpack install --replace /tmp/{{ virtbox_extpack | basename }}

  when: extpack_version.stdout != virtbox_version_minor
