---

- name: Suse family
  when: ansible_os_family == 'Suse'
  block:

    - name: Import the GPG key
      ansible.builtin.rpm_key:
        key: https://www.virtualbox.org/download/oracle_vbox.asc
        state: present

    - name: Retrieve repo definition
      ansible.builtin.get_url:
        url: https://download.virtualbox.org/virtualbox/rpm/opensuse/virtualbox.repo
        dest: /etc/zypp/repos.d/virtualbox.repo
        mode: '0644'

    - name: Refresh zypper
      ansible.builtin.command: zypper --gpg-auto-import-keys refresh
      changed_when: false

- name: RedHat family
  when: ansible_os_family == 'RedHat'
  block:

    - name: Import the GPG key
      ansible.builtin.rpm_key:
        key: https://www.virtualbox.org/download/oracle_vbox.asc
        state: present

    - name: Retrieve repo definition
      ansible.builtin.get_url:
        url: https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
        dest: /etc/yum.repos.d/virtualbox.repo
        mode: '0644'
      when: ansible_distribution == 'Fedora'

    - name: Change \$releasever in repo file
      ansible.builtin.replace:
        path: /etc/yum.repos.d/virtualbox.repo
        regexp: '\$releasever'
        replace: "{{ virtualbox_alternative_releasever }}"
      when:
        - ansible_distribution == 'Fedora'
        - virtualbox_alternative_releasever is defined

    - name: Get repo file (RedHat-family)
      ansible.builtin.get_url:
        url: https://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
        dest: /etc/yum.repos.d/virtualbox.repo
        mode: '0644'
      when: ansible_distribution != 'Fedora'

- name: Debian family
  when: ansible_os_family == 'Debian'
  block:

    - name: Download APT signing key
      ansible.builtin.get_url:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        dest: /tmp/oracle-virtualbox-2016.asc
        mode: "0644"
      changed_when: false

    - name: Convert APT key into binary format
      ansible.builtin.command:
        cmd: >-
          gpg
          --batch
          --yes
          --no-tty
          --dearmor
          -o /tmp/oracle-virtualbox-2016.gpg
          /tmp/oracle-virtualbox-2016.asc
      changed_when: false

    - name: Import Microsoft GPG key
      ansible.builtin.apt_key:
        state: present
        file: /tmp/oracle-virtualbox-2016.gpg
        keyring: /etc/apt/trusted.gpg.d/oracle-virtualbox-2016.gpg
      become: yes
      when: ansible_distribution_major_version | int < 12

    - name: Copy APT signing key into the proper drop-in directory
      ansible.builtin.copy:
        src: /tmp/oracle-virtualbox-2016.gpg
        dest: /etc/apt/trusted.gpg.d/oracle-virtualbox-2016.gpg
        remote_src: yes
        mode: "0644"
      when: ansible_distribution_major_version | int >= 12

    - name: Setup Microsoft APT repository  # noqa jinja[spacing]
      ansible.builtin.apt_repository:
        filename: virtualbox
        repo: >-
          {%- if ansible_distribution_major_version | int < 12 -%}
          deb
          [arch=amd64,arm64]
          https://download.virtualbox.org/virtualbox/debian
          {{ ansible_distribution_release }}
          contrib
          {%- else -%}
          deb
          [arch=amd64,arm64 signed-by=/etc/apt/trusted.gpg.d/oracle-virtualbox-2016.gpg]
          https://download.virtualbox.org/virtualbox/debian
          {{ ansible_distribution_release }}
          contrib
          {%- endif -%}
        state: present
      become: yes
      register: __apt_repository

    - name: Update package list  # noqa no-handler
      ansible.builtin.apt:
        update_cache: yes
      when: __apt_repository.changed

- name: Remove previous Virtualbox versions
  ansible.builtin.package:
    name: "{{ virtualbox_packages_obsolete }}"
    state: absent
  when: virtualbox_remove_old_versions | bool

- name: Install Virtualbox package
  ansible.builtin.package:
    name: "{{ virtualbox_packages }}"
    state: present

- name: Get Virtualbox extension packs installed
  ansible.builtin.include_tasks: extpack.yml

- name: Adding users to group vboxusers
  ansible.builtin.user:
    name: "{{ item }}"
    groups: vboxusers
    append: yes
  with_items: "{{ virtbox_users }}"
  when: virtbox_users is defined and virtbox_users|length > 0
