---

- name: Set OS specific defaults
  ansible.builtin.include_tasks: vars.yml

- name: Install virtualbox
  ansible.builtin.include_tasks: install.yml

- name: Get Virtualbox extension packs installed
  ansible.builtin.include_tasks: extpack.yml

- name: Perform addional configuration
  ansible.builtin.include_tasks: config.yml
