---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    molecule_driver: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') }}"
    virtualbox_disble_gpg_check: True
  tasks:
    - name: Include role 'ansible-role-virtualbox'
      ansible.builtin.include_role:
        name: ansible-role-virtualbox
